#!/usr/bin/env python3
"""Fix all card translations using slaythespire2.gg Chinese names"""
import re

card_map = {
    'Anger': '愤怒', 'Armaments': '武装', 'Barricade': '壁垒',
    'Bash': '痛击', 'Demon Form': '恶魔形态', 'Whirlwind': '旋风斩',
    'Body Slam': '全身撞击', 'Offering': '献祭', 'Fiend Fire': '恶魔之焰',
    'Juggernaut': '主宰', 'Colossus': '巨像', 'Dismantle': '拆卸',
    'Cruelty': '凌虐', 'Fight Me!': '与我一战！', 'Stoke': '添柴',
    'Expect a Fight': '备战', 'Crimson Mantle': '绯红披风',
    'Molten Fist': '熔融之拳', 'Iron Wave': '铁斩波',
    'Inflame': '燃烧', 'Break': '破击', 'Not Yet': '时候未到',
    'Hemokinesis': '御血术', 'Bloodletting': '放血', 'Tremble': '战栗',
    'Bully': '欺凌', 'Brand': '烙印', 'Bludgeon': '重锤',
    'Impervious': '坚不可摧', 'Battle Trance': '战斗专注',
    'Dominate': '支配', 'Spite': '怨恨', 'Cinder': '煤灰',
    'Blood Wall': '血墙', 'Dark Embrace': '黑暗之拥',
    'Feel No Pain': '无惧疼痛', 'Ashen Strike': '灰烬打击',
    'Pact\'s End': '契约终结', 'Evil Eye': '邪眼',
    'Burning Pact': '燃烧契约', 'Breakthrough': '突破',
    'Forgotten Ritual': '被遗忘的仪式', 'Corruption': '腐化',
    'Feed': '狂宴', 'Reaper': '收割', 'Flame Barrier': '火焰屏障',
    'Rupture': '撕裂', 'Hellraiser': '地狱狂徒', 'Stomp': '踩踏',
    'Uppercut': '上勾拳', 'Wild Strike': '狂乱撕扯', 'Brutality': '凶恶',
    'Pyre': '薪火之源', 'Immovable': '岿然不动', 'Conflagration': '狱火',
    'Mangle': '摧残', 'Berserk': '暴走', 'Spot Weakness': '优秀直觉',
    'Inferno': '地狱之火', 'Demonic Shield': '恶魔护盾', 'Rage': '狂怒',
    'Stone Armor': '岩石铠甲', 'Taunt': '挑衅', 'Vicious': '残酷',
    'Howl From Beyond': '彼岸咆哮', 'Second Wind': '重振精神',
    'Shrug It Off': '耸肩无视', 'Pommel Strike': '剑柄打击',
    'Twin Strike': '双重打击', 'Sword Boomerang': '飞剑回旋镖',
    'Perfected Strike': '完美打击', 'Headbutt': '头槌',
    'Havoc': '惊逃', 'Aggression': '跃跃欲试', 'One-Two Punch': '双打组合',
    'Juggling': '杂耍', 'Drum of Battle': '战鼓', 'Cascade': '倾泻',
    'Pillage': '劫掠', 'Thrash': '痛殴', 'Clash': '交锋',
    'Heavy Blade': '重剑', 'Rampage': '暴走', 'Sentinel': '哨卫',
    'True Grit': '坚毅', 'Warcry': '战吼', 'Thunderclap': '震荡波',
    'Unrelenting': '无情猛攻', 'Sweeping Strike': '万向斩',
    'Seeing Red': '怒火中烧', 'Reckless Charge': '肉盾',
    'Primal Force': '原始力量', 'Tear Asunder': '撕碎',
    'Setup Strike': '预备打击', 'Bulwark': '铸墙',
    # Silent
    'Acrobatics': '杂技', 'Backflip': '后空翻', 'Noxious Fumes': '毒雾',
    'Blade Dance': '刀刃之舞', 'Piercing Wail': '尖啸',
    'Footwork': '灵动步法', 'Corpse Explosion': '毒性爆发',
    'After Image': '余像', 'Adrenaline': '肾上腺素',
    'Burst': '爆发', 'Well-Laid Plans': '早有准备',
    'Wraith Form': '幽魂形态', 'Bullet Time': '子弹时间',
    'Nightmare': '夜魇', 'Catalyst': '触媒',
    'Calculated Gamble': '计算下注', 'Malaise': '萎靡',
    'Crippling Cloud': '致残毒云', 'Dagger Spray': '匕首雨',
    'Poisoned Stab': '带毒刺击', 'Deadly Poison': '致命毒药',
    'Bouncing Flask': '弹跳药瓶', 'Infinite Blades': '无尽刀刃',
    'Accuracy': '精准', 'Fan of Knives': '刀扇',
    'Knife Trap': '刀刃陷阱', 'Blade of Ink': '墨之刃',
    'Up My Sleeve': '袖里乾坤', 'Helical Dart': '螺旋钻击',
    'Speedster': '速行者', 'Murder': '谋杀',
    'Follow Through': '跟进', 'Memento Mori': '铭记死亡',
    'Survivor': '生存者', 'Tactician': '战术大师',
    'Reflex': '本能反应', 'Grand Finale': '华丽收场',
    'Blur': '残影', 'Skewer': '串刺', 'Flechettes': '飞镖',
    'Dash': '冲刺', 'Predator': '猎杀者', 'Sucker Punch': '出其不意',
    'Slice': '切割', 'Deflect': '偏折', 'Backstab': '背刺',
    'Bane': '灾祸', 'Escape Plan': '逃脱计划', 'Expertise': '独门技术',
    'Finisher': '终结技', 'Dodge and Roll': '闪躲翻滚',
    'Cloak and Dagger': '斗篷与匕首', 'Prepared': '准备',
    'Tools of the Trade': '必备工具', 'Phantom Blades': '幻影之刃',
    'Outbreak': '毒性爆发', 'Envenom': '涂毒', 'Abrasive': '磨蚀',
    'Haze': '迷雾', 'Flick-Flack': '连射', 'Ricochet': '连续反弹',
    'Untouchable': '触不可及', 'Expose': '暴露', 'Shadowmeld': '融入暗影',
    'Sly': '奇巧', 'Master Planner': '谋划专家', 'Serpent Form': '群蛇形态',
    'Corrosive Wave': '腐蚀波', 'Storm of Steel': '钢铁风暴',
    'Strangle': '勒紧', 'Dagger Throw': '投掷匕首',
    'Hidden Daggers': '隐秘匕首', 'Assassinate': '刺杀',
    'The Hunt': '狩猎', 'Tracking': '跟踪',
    'Precise Cut': '精确切击', 'Anticipate': '预判',
    'Leading Strike': '先制打击', 'Pounce': '猛扑',
    'Hand Trick': '手上技法', 'Pinpoint': '精密瞄准',
    # Defect
    'Glacier': '冰川', 'Cold Snap': '寒流', 'Defragment': '碎片整理',
    'Biased Cognition': '偏差认知', 'Echo Form': '回响形态',
    'Ball Lightning': '球状闪电', 'Barrage': '弹幕齐射',
    'All for One': '万物一心', 'Feral': '野性', 'Claw': '爪击',
    'Capacitor': '扩容', 'Shatter': '打碎', 'Hailstorm': '冰雹风暴',
    'Hotfix': '热修复', 'Synchronize': '同步', 'Coolheaded': '冷静头脑',
    'Ice Lance': '冰之长枪', 'Skim': '快速检索',
    'Consume': '能量汲取', 'Compile Driver': '编译冲击',
    'Beam Cell': '光束射线', 'Go for the Eyes': '眼部攻击',
    'Scrape': '刮削', 'Hologram': '全息影像', 'Boot Sequence': '启动流程',
    'Buffer': '缓冲', 'Creative AI': '创造性AI', 'Double Energy': '双倍能量',
    'Fusion': '聚变', 'Genetic Algorithm': '遗传算法',
    'Leap': '飞跃', 'Loop': '循环', 'Machine Learning': '机器学习',
    'Multi-Cast': '多重释放', 'Rainbow': '彩虹', 'Reboot': '重启',
    'Storm': '风暴', 'Sunder': '破灭', 'Sweeping Beam': '扫荡射线',
    'Tempest': '雷暴', 'White Noise': '白噪声', 'Zap': '电击',
    'Dualcast': '双重释放', 'Tesla Coil': '特斯拉线圈',
    'Hyperbeam': '超能光束', 'Signal Boost': '信号增强',
    'Flak Cannon': '散射炮', 'Smokestack': '烟囱', 'Compact': '压缩',
    'Spinner': '旋转工艺', 'Refract': '折射', 'Glasswork': '玻璃工艺',
    'Fight Through': '苦战', 'Trash to Treasure': '化废为宝',
    'Rocket Punch': '火箭飞拳', 'Adaptive Strike': '适应打击',
    'Boost Away': '高速脱离', 'Bulk Up': '巨石',
    'Chaos': '混沌', 'Charge Battery': '充电',
    'Chill': '冰寒', 'Consuming Shadow': '吞噬暗影',
    'Coolant': '冷却剂', 'Darkness': '漆黑',
    'Energy Surge': '能量涌动', 'Focused Strike': '集中打击',
    'FTL': '超越光速', 'Gunk Up': '污秽攻击',
    'Helix Drill': '螺旋钻击', 'Ignition': '引火',
    'Iteration': '迭代', 'Lightning Rod': '引雷针',
    'Meteor Strike': '陨石打击', 'Modded': '模组改造',
    'Momentum Strike': '趁势打击', 'Null': '空值',
    'Overclock': '超频', 'Quadcast': '四重释放',
    'Rip and Tear': '狂乱撕扯', 'Scavenge': '清淤',
    'Shadow Shield': '暗影之盾', 'Subroutine': '子程序',
    'Supercritical': '超临界态', 'Synthesis': '人工合成',
    'Thunder': '雷霆', 'TURBO': '内核加速',
    'Uproar': '骚动', 'Voltaic': '电流相生',
    # Necrobinder
    'Haunt': '纠缠', 'Capture Spirit': '捕捉灵魂',
    'Devour Life': '吞噬生命', 'Neurosurge': '精神过载',
    'End of Days': '末日降临', 'Necro Mastery': '亡灵精通',
    'Dirge': '挽歌', 'Grave Warden': '守墓人',
    'Severance': '分离', 'Seance': '降灵',
    'Soul Storm': '灵魂风暴', 'Death March': '死亡行军',
    'Squeeze': '紧勒', "Time's Up": '大限已至',
    "Death's Door": '死亡之门', 'Protector': '守护者',
    'Flatten': '压扁', 'Borrowed Time': '预借时间',
    'Invoke': '祈唤', 'Reave': '榨取', 'No Escape': '无处可逃',
    'Negative Pulse': '负能量脉冲', 'Deathbringer': '死亡使者',
    'Oblivion': '湮灭', 'Pull Aggro': '吸引仇恨',
    'Spur': '增生', "Sic 'Em": '去咬', 'Blight Strike': '荒疫打击',
    'Shroud': '厄运之衣', 'Scourge': '鞭打', 'Countdown': '倒数计时',
    'Reaper Form': '死神形态', 'Clean': '洁净', 'Dredge': '降灵',
    'Fear': '恐惧', 'Fetch': '啄击', 'Right Hand Hand': '得力助手',
    'Calcify': '钙化', 'Friendship': '友谊', 'Undeath': '不死',
    'Lethality': '致死性', "Banshee's Cry": '女妖之嚎',
    'Graveblast': '坟冢爆射', 'Defy': '违逆', 'Defile': '玷污',
    'Bodyguard': '护卫', 'Bone Shards': '碎骨',
    'Demesne': '领域', 'Enfeebling Touch': '弱化之触',
    'Glimpse Beyond': '彼岸一瞥', 'Gold Axe': '金斧',
    'High Five': '击掌', 'Melancholy': '忧郁',
    'Pagestorm': '书页风暴', 'Parse': '领会', 'Poke': '戳击',
    'Pull from Below': '亡魂牵引', 'Putrefy': '腐朽',
    'Rattle': '狠揍', 'Reanimate': '死者苏生',
    'Sculpting Strike': '雕琢打击', 'Shared Fate': '命运同担',
    'Sleight of Flesh': '血肉戏法', 'Snap': '响指',
    'Sentry Mode': '哨卫模式', 'Spirit of Ash': '灰烬之灵',
    'The Scythe': '巨镰', 'Transfigure': '重构',
    'Unleash': '出击', 'Veilpiercer': '刺破帷幕',
    'Wisp': '鬼火',
    # Regent
    'Sovereign Blade': '君王之剑', 'Cosmic Apathy': '宇宙冷漠',
    'Celestial Might': '天穹之力', 'Guiding Star': '引导之星',
    'Starlight Crash': '彗星', 'Meteor Fall': '流星雨',
    'Royal Guard': '皇家护盾',
    'Genesis': '创世纪', 'Big Bang': '大爆炸',
    'Furnace': '熔炉',
    'Conqueror': '征服者', 'Seven Stars': '七星',
    'Black Hole': '黑洞', 'Neutron Aegis': '中子护盾',
    'Beat into Shape': '锻打成型', 'Refine Blade': '淬炼刀刃',
    'Seeking Edge': '锋利边缘', 'Sword Sage': '剑圣',
    'Summon Forth': '征召上前', 'Spoils of Battle': '战利品',
    'Wrought in War': '战火铸就', 'Knockout Blow': '击倒',
    'Royal Gamble': '孤注一掷', 'Glow': '辉光',
    'Hidden Cache': '隐秘藏品', 'Gather Light': '收集光辉',
    'Solar Strike': '太阳打击', 'Shining Strike': '明耀打击',
    'Crescent Spear': '新月长矛',
    'Devastate': '毁灭', 'Dying Star': '星灭', 'Falling Star': '陨星',
    'Gamma Blast': '伽马爆破',
    'Quasar': '类星体', 'Resonance': '共鸣',
    'Stardust': '星尘', 'Venerate': '崇拜',
    'Alignment': '星位序列', 'Cloak of Stars': '群星斗篷',
    'Astral Pulse': '星界脉冲',
    'Child of the Stars': '群星之子', 'Radiate': '辐射',
    'Parry': '招架', 'Patter': '轻击',
    'Arsenal': '武器库', 'Bundle of Joy': '新生之喜',
    'Collision Course': '碰撞轨迹', 'Crash Landing': '迫降',
    'Heirloom Hammer': '传承之锤', 'Largesse': '慷慨捐助',
    'Manifest Authority': '君权自授', 'Pillar of Creation': '创世之柱',
    'Spectrum Shift': '光谱偏移', 'Supermassive': '超质量体',
    'Tyranny': '暴政',
}

files = ['ironclad.html', 'silent.html', 'defect.html', 'necrobinder.html', 'regent.html', 'cards.html', 'strategy.html']

for filepath in files:
    with open(filepath, 'r', encoding='utf-8') as f:
        content = f.read()
    changed = 0
    for en, zh in sorted(card_map.items(), key=lambda x: -len(x[0])):
        if en in content:
            content = content.replace(en, zh)
            changed += 1
    with open(filepath, 'w', encoding='utf-8') as f:
        f.write(content)
    print(f'{filepath}: {changed} cards fixed')

print('Done!')
